"""create successfully

Revision ID: 429cb2dbb18f
Revises: f8179c33bed4
Create Date: 2022-09-27 10:57:28.807875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429cb2dbb18f'
down_revision = 'f8179c33bed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
